techprober/cloud-estate

- .pre-commit-config.yaml
- README.md
- docs/pre-commit.md
- docs/terraform.md
Introduced pre-commit hooks to the repository to do pre-linting check
- https://github.com/antonbabenko/pre-commit-terraform
- https://pre-commit.com/
_some comments are appreciated_
> [Feature] - Introduced pre-commit hooks

- playbooks/README.md
- playbooks/ansible.cfg
- playbooks/arch-packages-update.yml
- playbooks/bin/arch-update
- playbooks/bin/brew-bootstrap
- playbooks/bin/brew-update
- playbooks/docs/ssh-configuration.md
- playbooks/homelab-apt-packages-update.yml
- playbooks/inventory/local.yml
- playbooks/inventory/main.yml
- playbooks/local-homebrew-update.yml
- playbooks/local-maintenance-reachability.yml
- playbooks/remote-apt-packages-update.yml
- playbooks/remote-maintenance-reachability.yml
- playbooks/requirements.yml
- playbooks/roles/apt.ops/tasks/apt-update.yml
- playbooks/roles/apt.ops/tasks/main.yml
- playbooks/roles/arch.update/tasks/main.yml
- playbooks/roles/arch.update/tasks/pacman-update.yml
- playbooks/roles/arch.update/tasks/yay-update.yml
- playbooks/roles/homebrew.ops/tasks/homebrew-update.yml
- playbooks/roles/homebrew.ops/tasks/main.yml
- playbooks/roles/maintenance.reachability/tasks/main.yml
- playbooks/roles/maintenance.reachability/tasks/reachability.yml
Added ansible modules
Feel free to add more module configurations or additional playbooks that can benefit the team.
> [Feat] Ansible Integration

- containerd/README.md
[Feat] Introduce Containerd Baremetal Installation Guideline
- [可以像 Docker 一样方便的使用 Containerd 吗？](https://www.51cto.com/article/679424.html)
> [Feat] Introduce Containerd Baremetal Installation Guideline

- containerd/README.md
Include Containerd-Baremetal Installation Guide for Ubuntu User
> [Feat] Containerd-Baremetal Installation Guide for Ubuntu User

- linux-tools/README.md
Added Lux to linux-tools
- https://github.com/iawia002/lux
> [Feat] Added Lux

- linux-tools/README.md
> [New] - Added docker-pi-hole

- linux-tools/README.md
> [New] - Added PVEDiscordDark

- linux-tools/README.md
> [new] Added github-status-updater

- linux-tools/README.md
> [new] Added smee.io

- docs/commit-msg-guide.md
> [Docs] Introduced Semantic Commit Msg Guide

- linux-tools/README.md
> [Feature] - Added bat

- linux-tools/README.md
> [Feature] - Added vivid

- references/README.md
> [Feature] - Added merging-vs-rebasing

- references/README.md
> [Feature] - Added techniques for rewriting Git history

- linux-tools/README.md
- feat(catagory): introduced productive-tools category
- feat(app): added marktext to productive-tools
- Link #
> [Feature] - Added marktext

- references/README.md
> [Feature] - Added vim category

- linux-tools/README.md
> [Feature] - More Vim/Neovim Plugins

- linux-tools/README.md
- references/README.md
> [Feature] - Added Wakatime references

- linux-tools/README.md
- linux-tools/assets/neovim.svg
- Add files via upload
- feat(linux-tools): added neovim icon
- Link #
> [Feature] - Added Neovim Icon

- linux-tools/README.md
> [Feature] - Added twilight

- linux-tools/README.md
> [Feature] - Added shade

- linux-tools/README.md
> [Feature] - Added indent-blankline.nvim

- linux-tools/README.md
> [Feature] - Added Hop

- linux-tools/README.md
> [Feature] - Added Argo Projects

- references/README.md
> [Feature] - Added container references article

- linux-tools/README.md
> [Feature] - Added buildah

- linux-tools/README.md
> [Feature] - Added Buildkit

- linux-tools/README.md
> [Feature] - Added awesome-argo

- linux-tools/README.md
> [Feature] - Added badges and reformat titles

- references/README.md
> [Feature] - Added ubuntu-cloud-images

- references/README.md
> [Feature] - Added homelab

- linux-tools/README.md
> [Feature] - Added CrowdSec

- linux-tools/README.md
> [Feature/linux-tools] - Added trousseau

- infrastructure/kubernetes-cluster/terragrunt.hcl
> [Feature/terraform-module] - Introduced k8s-agent provision template

- infrastructure/README.md
- infrastructure/kubernetes-cluster/master/terragrunt.hcl
- infrastructure/kubernetes-cluster/worker/terragrunt.hcl
- terraform-modules/proxmox-ve/vm-cluster/README.md
- terraform-modules/proxmox-ve/vm-cluster/resources.tf
- terraform-modules/proxmox-ve/vm-cluster/variables.tf
- terraform-modules/proxmox-ve/vm-mono/README.md
- terraform-modules/proxmox-ve/vm-mono/resources.tf
- terraform-modules/proxmox-ve/vm-mono/variables.tf
- feat(terraform-module): added nameserver variable
- updated README
- Link #
> [Feature/terraform-module] - Added nameserver variable to module

- linux-tools/README.md
> [Feature/linux-tools] - Added datree

- infrastructure/README.md
- infrastructure/proxmox-lxc/terragrunt.hcl
- terraform-modules/proxmox-ve/lxc-mono/README.md
- terraform-modules/proxmox-ve/lxc-mono/resources.tf
- terraform-modules/proxmox-ve/lxc-mono/variables.tf
Introduce `proxmox-lxc` terraform modules and provisioning example
> [Feature/terraform-module] - Added proxmox-lxc module

- playbooks/docker-install.yml
- playbooks/roles/docker.ops/tasks/docker-compose-install.yml
- playbooks/roles/docker.ops/tasks/docker-install.yml
- playbooks/roles/docker.ops/tasks/main.yml
- playbooks/vars/main.yml
> [feature/playbooks] - added docker-installation playbooks

- linux-tools/README.md
> [Feature/linux-tools] - added minio client cli tool

- linux-tools/README.md
> [Feature/linux-tools] - added hedgedoc

- linux-tools/README.md
> [Feature/linux-tools] - added dillinger

- linux-tools/README.md
> [Feature/linux-tools] - added stackedit

- packer-templates/README.md
- packer-templates/docker-ubuntu-20.04.json
- packer-templates/http/user-data
- packer-templates/playbooks/ansible.cfg
- packer-templates/playbooks/docker-post-provision.yml
- packer-templates/playbooks/post-provision.yml
- packer-templates/playbooks/post-provisioning.yml
- packer-templates/playbooks/tasks/docker-compose-install.yml
- packer-templates/playbooks/tasks/docker-install.yml
- packer-templates/playbooks/vars/main.yml
- packer-templates/ubuntu-2004.json
Introduce ubuntu-20.04 packer template with `Docker` and `docker-compose` pre-installed.
> [Feature/packer-template] - added docker tasks to post-installation playbook

- playbooks/roles/minio.ops/tasks/backup.yml
- playbooks/roles/minio.ops/tasks/main.yml
- playbooks/server-backup.yml
> [Feature/playbooks] - added minio.ops playbook

- playbooks/install_new_key.yml
- playbooks/roles/keys.ops/tasks/install_public_keys.yml
- playbooks/roles/keys.ops/tasks/main.yml
- playbooks/vars/main.yml
> [Feature/playbooks] - added keys.ops playbook

- infrastructure/proxmox-vm/ubuntu-server-test/terragrunt.hcl
- terraform-modules/proxmox-ve/vm-cluster/README.md
- terraform-modules/proxmox-ve/vm-cluster/resources.tf
- terraform-modules/proxmox-ve/vm-cluster/variables.tf
- terraform-modules/proxmox-ve/vm-mono/README.md
- terraform-modules/proxmox-ve/vm-mono/resources.tf
- terraform-modules/proxmox-ve/vm-mono/variables.tf
> [Feature/terraform-modules] - Add vm_network_netmask param

- playbooks/README.md
- playbooks/roles/minio.ops/tasks/main.yml
- playbooks/roles/minio.ops/tasks/setup.yml
- docs: updated ansible-lint installation
- docs: added ansible check mode
- initial commit
- Link #
> [Feature/playbooks] - Add Minio Client Roles

- infrastructure/kubernetes-cluster/master/terragrunt.hcl
- infrastructure/kubernetes-cluster/worker/terragrunt.hcl
- infrastructure/proxmox-vm/ubuntu-server-test/terragrunt.hcl
- terraform-modules/proxmox-ve/vm-cluster/README.md
- terraform-modules/proxmox-ve/vm-cluster/resources.tf
- terraform-modules/proxmox-ve/vm-cluster/variables.tf
- terraform-modules/proxmox-ve/vm-mono/README.md
- terraform-modules/proxmox-ve/vm-mono/resources.tf
- terraform-modules/proxmox-ve/vm-mono/variables.tf
Introduced VLAN tagging to a specific interface
> [Feature/terraform-modules]: Add VLAN Tagging

- playbooks/homelab-apt-packages-update.yml
- playbooks/homelab-apt-proxy-setup.yml
- playbooks/install_new_key.yml
- playbooks/roles/keys.ops/tasks/install_public_keys.yml
- playbooks/roles/keys.ops/tasks/main.yml
- playbooks/roles/server.ops/key.ops/tasks/install_public_keys.yml
- playbooks/roles/server.ops/key.ops/variables/main.yml
- playbooks/roles/server.ops/proxy.ops/tasks/main.yml
- playbooks/roles/server.ops/proxy.ops/tasks/setup.yml
- playbooks/roles/server.ops/reboot.ops/tasks/main.yml
- playbooks/roles/server.ops/reboot.ops/tasks/reboot.yml
- feat(playbook): introduced proxy.ops module
- fix: updated key.ops roles
- fix: updated general playbook configs
- Link #
> [Feature/playbooks] - Add server.ops roles

- linux-tools/README.md
> [Feature/linux-tools/kubernetes] - Added kubectx

- playbooks/minio-setup.yml
- playbooks/roles/minio.ops/setup.ops/tasks/authenticate.yml
- playbooks/roles/minio.ops/setup.ops/tasks/main.yml
- playbooks/roles/minio.ops/setup.ops/variables/main.yml
- playbooks/server-backup.yml
> [Feature/playbook] - Introduced Minio setup roles

- linux-tools/README.md
> [Feature/linux-tools] - Introduced kpack

- linux-tools/README.md
> [Feature/linux-tools] - Introduced v2rayA

- linux-tools/README.md
> [Feature/linux-tools] - Introduced doggo

- packer-templates/cn-docker-ubuntu-2204.json
- packer-templates/cn-http/user-data
- packer-templates/cn-ubuntu-2204.json
- packer-templates/docker-ubuntu-20.04.json
- packer-templates/docker-ubuntu-22.04.json
- packer-templates/ubuntu-2004.json
- packer-templates/ubuntu-2204.json
Introduced cn-ubuntu-2204 templates with moded apt source (ustc.cn)
- fix: extend timeout from 30mins to 40mins
- feat: added cn-http as base cloud-init template
- feat: introduced cn-ubuntu templates with moded apt sources list(ustc.cn)
```
cn-http
├── meta-data
└── user-data
cn-docker-ubuntu-2204.json
cn-ubuntu-2204.json
```
> [Feature/packer] - Introduced cn-ubuntu-templates

- packer-templates/example-ubuntu-2004.vars.json
- packer-templates/example-ubuntu-2204.vars.json
Set default storage location from `local` to `local-lvm`
> [Feature/packer] - Fix default storage location

- playbooks/minio-backup.yml
- playbooks/roles/minio.ops/setup.ops/tasks/authenticate.yml
- playbooks/roles/minio.ops/setup.ops/tasks/install_jq.yml
- playbooks/roles/minio.ops/setup.ops/tasks/main.yml
Add steps to update minio server if default_uri changes
- feat(playbook/minio.ops): introduced jq install task
- fix(playbook): set variable in global scope
- feat(playbook/minio.ops): added steps to update minio server
> [Feature/playbooks/minio.ops] - Add steps to update minio server if default_uri changes

- playbooks/install-apt-packages.yml
- playbooks/roles/apt.ops/install-packages.ops/tasks/info.yml
- playbooks/roles/apt.ops/install-packages.ops/tasks/install.yml
- playbooks/roles/apt.ops/install-packages.ops/tasks/main.yml
- playbooks/roles/apt.ops/install-packages.ops/tasks/verify.yml
Introduce a role tailored to installing a custom list of apt packages (works with DEBIAN based system)
Define the list of software packages you wish to be installed on the target remote servers in the playbook with the `vars` attribute as shown in the following:
```yaml
---
- name: Install packages with apt
hosts: all
become: yes
vars:
- packages: # Packages to be installed
- vim
- neofetch
roles:
- role: ./roles/apt.ops/install-packages.ops/
```
To run the playbook:
```bash
ansible-playbook -K -i <your inventory list> $HOME/workspace/cloud-estate/playbooks/install-apt-packages.yml
```
Sample execution logs:
<details><summary>ansible-play.logs</summary>
</br>
```
PLAY [Install packages with apt] ***********************************************
TASK [Gathering Facts] …
```
> [Feature/playbook] - Introduce apt-pkg-install role

- .pre-commit-config.yaml
- README.md
- feat(pre-commit): added end of file hook
- chore(pre-commit): updated pre-commit hook version
- fix(pre-commit): removed ansible-lint hook
- docs: removed pre-commit homebrew installation
> [Patch/pre-commit] - Patch to pre-commit hooks

- infrastructure/proxmox-lxc/terragrunt.hcl
- terraform-modules/proxmox-ve/lxc-basic/resources.tf
- terraform-modules/proxmox-ve/lxc-clone/resources.tf
- terraform-modules/proxmox-ve/vm-cluster/resources.tf
- terraform-modules/proxmox-ve/vm-mono/resources.tf
- fix: fixed module referrencing
- chore(provider): updated plugin provider to v2.9.10
> [Patch/infrastructure] Fix module referencing, upgrade proxmox plugin version

- terraform-modules/proxmox-ve/lxc-basic/README.md
- terraform-modules/proxmox-ve/lxc-basic/main.tf
- terraform-modules/proxmox-ve/lxc-basic/resources.tf
- terraform-modules/proxmox-ve/lxc-clone/README.md
- terraform-modules/proxmox-ve/lxc-clone/main.tf
- terraform-modules/proxmox-ve/lxc-clone/resources.tf
- terraform-modules/proxmox-ve/vm-cluster/README.md
- terraform-modules/proxmox-ve/vm-cluster/main.tf
- terraform-modules/proxmox-ve/vm-cluster/resources.tf
- terraform-modules/proxmox-ve/vm-mono/README.md
- terraform-modules/proxmox-ve/vm-mono/main.tf
- terraform-modules/proxmox-ve/vm-mono/resources.tf
- chore(terraform-modules): upgrade provider from v2.9.10 to v.2.9.11
- docs(terraform-modules): updated module definition
> [Chore] Bumb up terraform-proxmox-provider to v2.9.11

- linux-tools/README.md
- feat(cmd-utils): add fd
- feat(docker-images): add whoami
> linux tools/docker images

- linux-tools/README.md
- feat(cmd-utils): add fd
- feat(cmd-utils): add tldr
> [Feature/linux-tools/cmd-utils] Add tldr

- cloud-native/kind/README.md
- cloud-native/kind/app.yaml
- cloud-native/kind/kind.yaml
- feat: added sample app
- feat: added sample config
- docs: added README
- doc: updated README
> [Feature/cloud-native] Add kind

- cloud-native/kind/README.md
- cloud-native/kind/kind.yaml
- feat(cloud-native/kind): added extra configs to enable external access
- doc(cloud-native/kind): added networking configuration as reference
> [Feature/cloud-native/kind] External Access

- cloud-native/kind/README.md
- cloud-native/kind/app.yaml
- doc(cloud-native/kind): added default ingress class
- feat(cloud-native/kind): added option to specify ingress class
> [Feature/cloud-native/kind] Add ingress class option

- terraform-modules/proxmox-ve/lxc-basic/resources.tf
- terraform-modules/proxmox-ve/lxc-basic/variables.tf
- terraform-modules/proxmox-ve/vm-mono/resources.tf
- patch: added optional firewall settings
- fix-up: fixed vm firewall settings
> [Patch/terraform-modules] Fix firewall option

- linux-tools/README.md
feat(linux-tools/cmd-utils): added gopass
> [Feature/linux-tools/cmd-utils] Add gopass

- packer-templates/README.md
- packer-templates/bake
- doc(packer-template): added quick-use guide
- feat(packer-template): add custom host config path as a new cli-option
> feat(packer/bake-callable-update): add custom host config path as a new cli-option

- linux-tools/README.md
- feat(linux-tools/cloudnative): add bane
- feat(linux-tools/cloudnative): add goproxy
> feat(linux-tools/cloudnative): add goproxy

- manifests/juicefs/examples/dynamic-provision-deployment.yaml
- manifests/juicefs/examples/static-provision-deployment.yaml
- manifests/juicefs/k0s-helm-values.yaml
- feat: add dynamic-provision-deployment
- feat: add static-provision-deployment
- feat: add k0s-helm-values.yaml
> feat(manifests/juicefs): add static/dynamic-provision-deployment examples

- linux-tools/README.md
- feat(linux-tools/cloudnative): add flux2 and extras
- feat(linux-tools/kubernetes-related): add geek-cookbooks
> feat(linux-tools/cloudnative): add fluxcd and flux-extras

- linux-tools/README.md
- feat(linux-tools/golang): add log15
- feat(linux-tools/golang): add learn-go-with-tests
> feat(linux-tools/golang): add more go pkgs

- packer-templates/README.md
- packer-templates/bakery-config.json
- packer-templates/http/user-data
- packer-templates/proxmox-packer-template.pkr.hcl
updated the procedure of creating ubuntu template on Proxmox 8.0
- updated README
- updated ubuntu base iso version from 22.04.1 to 22.04.3
- fixed a few errors when creating template using packer:
> patch: latest Packer deployment for pve8

- linux-tools/README.md
> add transparent.nvim
